// Every demo: a classic game mechanic turned into a math game. The hub lists
// these; opening one loads src/games/<id>.js (see kit.js for what a game gets).

export const GROUPS = [
  { id: 'arcade', name: 'Arcade' },
  { id: 'puzzle', name: 'Puzzle' },
  { id: 'board', name: 'Board & card' },
  { id: 'other', name: 'Other genres' },
];

export const DEMOS = [
  // ---- arcade
  { id: 'tetris', group: 'arcade', icon: '🧱', name: 'Times Tetris', classic: 'Tetris', idea: 'Falling rectangles: say the area to lock each one in, and fill whole rows to clear them.', how: ['← → move, ↑ turns, ↓ drops faster (Space drops at once).', 'When it lands, type its area (rows × columns) to lock it in.', 'Wrong: it crumbles away. Fill a whole row to clear it.'] },
  { id: 'invaders', group: 'arcade', icon: '👾', name: 'Fact Invaders', classic: 'Space Invaders', idea: 'A question loads your cannon; shoot the alien carrying the answer.', how: ['← → move your cannon (or drag).', 'Space (or tap Fire) shoots at the alien above you.', 'Hit the alien with the answer. Wrong aliens, or aliens landing, cost a heart!'] },
  { id: 'breakout', group: 'arcade', icon: '🏓', name: 'Product Breakout', classic: 'Breakout', idea: 'Your paddle shows a number; the ball only breaks bricks whose fact equals it.', how: ['← → or the mouse move the paddle.', 'Bricks show facts like 3 × 4. Only bricks equal to the paddle’s number break.', 'Break all the matching bricks to get a new number.'] },
  { id: 'pacman', group: 'arcade', icon: '🟡', name: 'Multiple Muncher', classic: 'Pac-Man', idea: 'Eat the dots that are multiples of a number; ghosts chase you.', how: ['Arrow keys move through the maze.', 'Eat only the multiples of the number at the top.', 'Wrong dots and ghosts cost a heart.'] },
  { id: 'frogger', group: 'arcade', icon: '🐸', name: 'Answer Hopper', classic: 'Frogger', idea: 'Hop across the river on the log with the right answer.', how: ['Each lane asks a question.', '← → pick a log in the next lane (or tap it); ↑ hops onto it.', 'Land on the right answer or splash!'] },
  { id: 'whack', group: 'arcade', icon: '🔨', name: 'Whack-a-Multiple', classic: 'Whack-a-Mole', idea: 'Moles pop up with numbers: whack only the ones in the table.', how: ['Click or tap a mole to whack it.', 'Whack only the multiples of the number shown.', '30 seconds: how many can you get?'] },
  { id: 'flappy', group: 'arcade', icon: '🐦', name: 'Flappy Facts', classic: 'Flappy Bird', idea: 'Fly through the gap marked with the right answer.', how: ['Space, click or tap flaps.', 'Each wall has gaps with numbers: fly through the answer.', 'Wrong gap or a crash costs a heart.'] },
  { id: 'asteroids', group: 'arcade', icon: '☄️', name: 'Factor Asteroids', classic: 'Asteroids', idea: 'Shoot a number and it splits into two factors; blast them down to primes.', how: ['← → turn, ↑ thrust, Space shoots.', 'A hit number splits into two factors (24 → 4 and 6).', 'Primes vanish when hit. Clear the field!'] },
  // ---- puzzle
  { id: 'twenty48', group: 'puzzle', icon: '🔢', name: '2048 ×2', classic: '2048', idea: 'Slide tiles; equal tiles merge into their double. Say the double to merge them.', how: ['Arrow keys or swipes slide all the tiles.', 'Two equal tiles merge: pick or type their double (14 + 14 = 28).', 'Reach the goal tile (64 on Easy), or as far as you can.'] },
  { id: 'match3', group: 'puzzle', icon: '🍬', name: 'Product Match', classic: 'Match-3', idea: 'Pick three tiles in a row that multiply to the target.', how: ['Tap three touching tiles in a line.', 'Their product must equal the target.', 'Matches clear and new tiles fall in.'] },
  { id: 'memory', group: 'puzzle', icon: '🃏', name: 'Fact Pairs', classic: 'Memory', idea: 'Flip cards to match each fact with its answer.', how: ['Tap two cards to flip them.', 'A fact (6 × 7) and its answer (42) are a pair.', 'Find all the pairs in as few tries as you can.'] },
  { id: 'minesweeper', group: 'puzzle', icon: '💣', name: 'Multiple Sweeper', classic: 'Minesweeper', idea: 'Mines hide under multiples; the clues count the multiples around each square.', how: ['Every square shows a number. Tap to open it; right-click, long-press or Flag mode to flag.', 'Mines are the multiples of the number shown: flag them, open the rest.', 'Each opened square says how many mines touch it.'] },
  { id: 'kenken', group: 'puzzle', icon: '🧮', name: 'Times Cages', classic: 'KenKen', idea: 'Fill the grid so each row and column has each number once and every cage multiplies to its clue.', how: ['Tap a square, then a number.', 'Rows and columns use each number once.', 'The numbers in a cage multiply to its clue.'] },
  { id: 'nonogram', group: 'puzzle', icon: '🖼️', name: 'Picture Products', classic: 'Nonogram', idea: 'Solve facts to learn which squares to fill; a picture appears.', how: ['Each row and column clue is a fact: its answer is how many squares to fill in one block.', 'Tap squares to fill them.', 'Get every row and column right to reveal the picture.'] },
  { id: 'tangram', group: 'puzzle', icon: '🧩', name: 'Area Puzzle', classic: 'Tangram / pentominoes', idea: 'Fill a shape exactly with rectangles of the right areas.', how: ['Pick a rectangle from the tray and tap where it goes.', 'Its area must fit the space exactly.', 'Fill the whole shape with no gaps.'] },
  // ---- board and card
  { id: 'connect4', group: 'board', icon: '🔴', name: 'Four in a Row', classic: 'Connect Four', idea: 'Move a marker along the factor strip; the product is the square you claim.', how: ['The two markers on the strip multiply to a square on the board.', 'On your turn, move one marker, then tap that product on the board to claim it.', 'Four in a row wins. The CPU plays too.'] },
  { id: 'ladders', group: 'board', icon: '🪜', name: 'Snakes & Ladders', classic: 'Snakes and Ladders', idea: 'Answer a fact to roll; answer right on a ladder to climb it, or on a snake to dodge it.', how: ['Answer the fact to roll the die (wrong: you move just 1 square).', 'Land on a ladder: answer to climb it. Land on a snake: answer right to dodge it.', 'First to 50 wins. The CPU races you.'] },
  { id: 'battleship', group: 'board', icon: '🚢', name: 'Fact Battleship', classic: 'Battleship', idea: 'Fire at a square by naming its product.', how: ['Rows and columns are numbers; each square is their product.', 'To fire, type the product of the square you picked.', 'Sink the CPU’s ships before it sinks yours.'] },
  { id: 'war', group: 'board', icon: '🂡', name: 'Product War', classic: 'War / Top Trumps', idea: 'Both flip two cards; the bigger product wins the round.', how: ['Flip: you and the CPU get two cards each.', 'Say which product is bigger (and what yours is).', 'The bigger product wins all four cards. Most cards after 10 rounds wins.'] },
  { id: 'bingo', group: 'board', icon: '🎱', name: 'Times Bingo', classic: 'Bingo', idea: 'Facts are called; mark their answers on your card.', how: ['The caller reads out a fact (6 × 8).', 'Tap its answer on your card if you have it.', 'Five in a row: Bingo!'] },
  { id: 'dominoes', group: 'board', icon: '🁫', name: 'Fact Dominoes', classic: 'Dominoes', idea: 'Match domino ends that are equal: 3 × 4 next to 12 or 2 × 6.', how: ['Tap a domino in your hand, then an end of the line.', 'The touching ends must be equal.', 'Play all your dominoes first to win.'] },
  // ---- other genres
  { id: 'towers', group: 'other', icon: '🏰', name: 'Fact Towers', classic: 'Tower defense', idea: 'Answer facts to power your towers; harder facts make stronger shots.', how: ['Monsters walk the path.', 'Answer a fact to fire; the bigger the answer, the stronger the shot.', 'Don’t let 10 monsters through.'] },
  { id: 'racing', group: 'other', icon: '🏎️', name: 'Fact Racer', classic: 'Racing', idea: 'Every right answer is a boost; beat the CPU cars to the flag.', how: ['Answer the questions as fast as you can.', 'Each right answer boosts your car.', 'Wrong answers slow you down.'] },
  { id: 'rhythm', group: 'other', icon: '🥁', name: 'Skip-Count Beats', classic: 'Rhythm', idea: 'Skip-count on the beat: tap the next multiple as it reaches the line.', how: ['Numbers fall in lanes to a beat.', 'Tap (or press 1–4) the lane with the next multiple as it reaches the line.', 'Keep the count going!'] },
  { id: 'clicker', group: 'other', icon: '🍪', name: 'Multiplier Bakery', classic: 'Idle / clicker', idea: 'Bake cookies; buy ovens and recipes by working out how many you’ll make.', how: ['Click the cookie to bake.', 'Buy upgrades: more ovens and better recipes.', 'To buy, say the new total per second (ovens × cookies each).'] },
  { id: 'platformer', group: 'other', icon: '🏃', name: 'Jump the Answer', classic: 'Platformer', idea: 'Jump onto the platform with the right answer.', how: ['← → run, ↑ or Space jumps.', 'Platforms carry numbers: land on the answer.', 'Wrong platforms crumble!'] },
];

export const byId = (id) => DEMOS.find((d) => d.id === id) || null;
